import 'package:tuple/tuple.dart';

const List<Tuple3<String, String, int>> instruments = [
  Tuple3('Piano', 'Acoustic Piano', 0),
  Tuple3('Piano', 'BrtAcou Piano', 1),
  Tuple3('Piano', 'ElecGrand Piano', 2),
  Tuple3('Piano', 'Honky Tonk Piano', 3),
  Tuple3('Piano', 'Elec.Piano 1', 4),
  Tuple3('Piano', 'Elec.Piano 2', 5),
  Tuple3('Piano', 'Harsichord', 6),
  Tuple3('Piano', 'Clavichord', 7),
  Tuple3('Chromatic Percussion', 'Celesta', 8),
  Tuple3('Chromatic Percussion', 'Glockenspiel', 9),
  Tuple3('Chromatic Percussion', 'Music Box', 10),
  Tuple3('Chromatic Percussion', 'Vibraphone', 11),
  Tuple3('Chromatic Percussion', 'Marimba', 12),
  Tuple3('Chromatic Percussion', 'Xylophone', 13),
  Tuple3('Chromatic Percussion', 'Tubular Bells', 14),
  Tuple3('Chromatic Percussion', 'Dulcimer', 15),
  Tuple3('Organ', 'Drawbar Organ', 16),
  Tuple3('Organ', 'Perc. Organ', 17),
  Tuple3('Organ', 'Rock Organ', 18),
  Tuple3('Organ', 'Church Organ', 19),
  Tuple3('Organ', 'Reed Organ', 20),
  Tuple3('Organ', 'Accordian', 21),
  Tuple3('Organ', 'Harmonica', 22),
  Tuple3('Organ', 'Tango Accordian', 23),
  Tuple3('Guitar', 'Acoustic Guitar', 24),
  Tuple3('Guitar', 'SteelAcous. Guitar', 25),
  Tuple3('Guitar', 'El.Jazz Guitar', 26),
  Tuple3('Guitar', 'Electric Guitar', 27),
  Tuple3('Guitar', 'El. Muted Guitar', 28),
  Tuple3('Guitar', 'Overdriven Guitar', 29),
  Tuple3('Guitar', 'Distortion Guitar', 30),
  Tuple3('Guitar', 'Guitar Harmonic', 31),
  Tuple3('Bass', 'Acoustic Bass', 32),
  Tuple3('Bass', 'El.Bass Finger', 33),
  Tuple3('Bass', 'El.Bass Pick', 34),
  Tuple3('Bass', 'Fretless Bass', 35),
  Tuple3('Bass', 'Slap Bass 1', 36),
  Tuple3('Bass', 'Slap Bass 2', 37),
  Tuple3('Bass', 'Synth Bass 1', 38),
  Tuple3('Bass', 'Synth Bass 2', 39),
  Tuple3('Strings', 'Violin', 40),
  Tuple3('Strings', ' Viola', 41),
  Tuple3('Strings', 'Cello', 42),
  Tuple3('Strings', 'Contra Bass', 43),
  Tuple3('Strings', 'Tremelo Strings', 44),
  Tuple3('Strings', 'Pizz. Strings', 45),
  Tuple3('Strings', 'Orch. Strings', 46),
  Tuple3('Strings', 'Timpani', 47),
  Tuple3('Ensemble', 'String Ens.1', 48),
  Tuple3('Ensemble', 'String Ens.2', 49),
  Tuple3('Ensemble', 'Synth.Strings 1', 50),
  Tuple3('Ensemble', 'Synth.Strings 2', 51),
  Tuple3('Ensemble', 'Choir Aahs', 52),
  Tuple3('Ensemble', 'Voice Oohs', 53),
  Tuple3('Ensemble', 'Synth Voice', 54),
  Tuple3('Ensemble', 'Orchestra Hit', 55),
  Tuple3('Brass', 'Trumpet', 56),
  Tuple3('Brass', 'Trombone', 57),
  Tuple3('Brass', 'Tuba', 58),
  Tuple3('Brass', 'Muted Trumpet', 59),
  Tuple3('Brass', 'French Horn', 60),
  Tuple3('Brass', 'Brass Section', 61),
  Tuple3('Brass', 'Synth Brass 1', 62),
  Tuple3('Brass', 'Synth Brass 2', 63),
  Tuple3('Reed', 'Soprano Sax', 64),
  Tuple3('Reed', 'Alto Sax', 65),
  Tuple3('Reed', 'Tenor Sax', 66),
  Tuple3('Reed', 'Baritone Sax', 67),
  Tuple3('Reed', 'Oboe', 68),
  Tuple3('Reed', 'English Horn', 69),
  Tuple3('Reed', 'Bassoon', 70),
  Tuple3('Reed', 'Clarinet', 71),
  Tuple3('Pipe', 'Piccolo', 72),
  Tuple3('Pipe', 'Flute', 73),
  Tuple3('Pipe', 'Recorder', 74),
  Tuple3('Pipe', 'Pan Flute', 75),
  Tuple3('Pipe', 'Blown Bottle', 76),
  Tuple3('Pipe', 'Shakuhachi', 77),
  Tuple3('Pipe', 'Whistle', 78),
  Tuple3('Pipe', 'Ocarina', 79),
  Tuple3('Synth Lead', 'Lead1 Square', 80),
  Tuple3('Synth Lead', 'Lead2 Sawtooth', 81),
  Tuple3('Synth Lead', 'Lead3 Calliope', 82),
  Tuple3('Synth Lead', 'Lead4 Chiff', 83),
  Tuple3('Synth Lead', 'Lead5 Charang', 84),
  Tuple3('Synth Lead', 'Lead6 Voice', 85),
  Tuple3('Synth Lead', 'Lead7 Fifths', 86),
  Tuple3('Synth Lead', 'Lead8 Bass Ld', 87),
  Tuple3('Synth Pad', 'Pad1 New Age', 88),
  Tuple3('Synth Pad', 'Pad2 Warm', 89),
  Tuple3('Synth Pad', 'Pad3 Polysynth', 90),
  Tuple3('Synth Pad', 'Pad4 Choir', 91),
  Tuple3('Synth Pad', 'Pad5 Bowed', 92),
  Tuple3('Synth Pad', 'Pad6 Metallic', 93),
  Tuple3('Synth Pad', 'Pad7 Halo', 94),
  Tuple3('Synth Pad', 'Pad8 Sweep', 95),
  Tuple3('Synth F/X', 'FX1 Rain', 96),
  Tuple3('Synth F/X', 'FX2 Soundtrack', 97),
  Tuple3('Synth F/X', 'FX3 Crystal', 98),
  Tuple3('Synth F/X', 'FX4 Atmosphere', 99),
  Tuple3('Synth F/X', 'FX5 Brightness', 100),
  Tuple3('Synth F/X', 'FX6 Goblins', 101),
  Tuple3('Synth F/X', 'FX7 Echoes', 102),
  Tuple3('Synth F/X', 'FX8 Sci-Fi', 103),
  Tuple3('Ethnic', 'Sitar', 104),
  Tuple3('Ethnic', 'Banjo', 105),
  Tuple3('Ethnic', 'Shamisen', 106),
  Tuple3('Ethnic', 'Koto', 107),
  Tuple3('Ethnic', 'Kalimba', 108),
  Tuple3('Ethnic', ' Bagpipe', 109),
  Tuple3('Ethnic', ' Fiddle', 110),
  Tuple3('Ethnic', ' Shanai', 111),
  Tuple3('Percussive', 'TinkerBell', 112),
  Tuple3('Percussive', 'Agogo', 113),
  Tuple3('Percussive', 'SteelDrums', 114),
  Tuple3('Percussive', 'Woodblock', 115),
  Tuple3('Percussive', 'TaikoDrum', 116),
  Tuple3('Percussive', 'Melodic Tom', 117),
  Tuple3('Percussive', 'SynthDrum', 118),
  Tuple3('Percussive', 'Reverse Cymbal', 119),
  Tuple3('Sound F/X', 'Guitar Fret Noise', 120),
  Tuple3('Sound F/X', 'Breath Noise', 121),
  Tuple3('Sound F/X', 'Seashore', 122),
  Tuple3('Sound F/X', 'BirdTweet', 123),
  Tuple3('Sound F/X', 'Telephone', 124),
  Tuple3('Sound F/X', 'Helicopter', 125),
  Tuple3('Sound F/X', 'Applause', 126),
  Tuple3('Sound F/X', 'Gunshot', 127),
];
